Repository hygieia/hygieia, pull requests merged in 2018-11, with the labels that each got.

#2550 Hygieia Jenkins Plugin Enhancements - v2.1.6
  api/src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
  api/src/main/java/com/capitalone/dashboard/rest/BuildController.java
  api/src/main/java/com/capitalone/dashboard/service/BuildService.java
  api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/DashboardService.java
  api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java
  api/src/test/java/com/capitalone/dashboard/service/BuildServiceTest.java
  core/src/main/java/com/capitalone/dashboard/response/BuildDataCreateResponse.java
  hygieia-jenkins-plugin/pom.xml
  hygieia-jenkins-plugin/src/main/java/hygieia/builder/CommitBuilder.java
  hygieia-jenkins-plugin/src/main/java/hygieia/builder/CucumberTestBuilder.java
  hygieia-jenkins-plugin/src/main/java/hygieia/builder/DeployBuilder.java
  hygieia-jenkins-plugin/src/main/java/hygieia/utils/HygieiaUtils.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/DefaultHygieiaService.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaGlobalListener.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaPublisher.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/HygieiaService.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaArtifactPublishStep.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStep.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaDeployPublishStep.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaSonarPublishStep.java
  hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaTestPublishStep.java
  hygieia-jenkins-plugin/src/main/resources/jenkins/plugins/hygieia/HygieiaPublisher/global.jelly
  hygieia-jenkins-plugin/src/main/webapp/help-globalConfig-hygieiaAppUrl.html
  hygieia-jenkins-plugin/src/main/webapp/help-globalConfig-hygieiaBuildServerUrl.html
  hygieia-jenkins-plugin/src/main/webapp/help-globalConfig-hygieiaPublishSonarData.html
  hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaGlobalListenerTest.java
  hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaJobListenerTest.java
  hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/HygieiaPublisherTest.java
  hygieia-jenkins-plugin/src/test/java/jenkins/plugins/hygieia/workflow/HygieiaCodeQualityPublishStepExecutionTest.java
Labels: enhancement

#2534 Delete all test bug
  api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java
Labels: bug

#2547 The Github WebHook API
  api/src/main/java/com/capitalone/dashboard/auth/webhook/github/GithubWebHookAuthService.java
  api/src/main/java/com/capitalone/dashboard/auth/webhook/github/GithubWebHookAuthServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/auth/webhook/github/GithubWebHookRequestFilter.java
  api/src/main/java/com/capitalone/dashboard/config/RestApiAppConfig.java
  api/src/main/java/com/capitalone/dashboard/config/WebSecurityConfig.java
  api/src/main/java/com/capitalone/dashboard/logging/LoggingFilter.java
  api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/DynamicPipelineServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/EncryptionServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/PipelineServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/settings/ApiSettings.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubHookController.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubHookService.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubHookServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubIssueV3.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPayloadType.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GitHubV3.java
  api/src/main/java/com/capitalone/dashboard/webhook/github/GraphQLQuery.java
  api/src/main/java/com/capitalone/dashboard/webhook/settings/GitHubWebHookSettings.java
  api/src/main/java/com/capitalone/dashboard/webhook/settings/WebHookSettings.java
  api/src/test/java/com/capitalone/dashboard/auth/DefaultAuthenticationTest.java
  api/src/test/java/com/capitalone/dashboard/auth/webhook/github/GithubWebHookRequestFilterTest.java
  api/src/test/java/com/capitalone/dashboard/logging/LoggingFilterTest.java
  api/src/test/java/com/capitalone/dashboard/service/BuildServiceTest.java
  api/src/test/java/com/capitalone/dashboard/service/DynamicPipelineServiceImplTest.java
  api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubCommitV3Test.java
  api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubIssueV3Test.java
  api/src/test/java/com/capitalone/dashboard/webhook/github/GitHubPullRequestV3Test.java
  core/src/main/java/com/capitalone/dashboard/client/RestAuthType.java
  core/src/main/java/com/capitalone/dashboard/client/RestClient.java
  core/src/main/java/com/capitalone/dashboard/client/RestUserInfo.java
  core/src/main/java/com/capitalone/dashboard/model/SCM.java
  core/src/main/java/com/capitalone/dashboard/model/webhook/github/GitHubParsed.java
  core/src/main/java/com/capitalone/dashboard/model/webhook/github/GitHubRepo.java
  core/src/main/java/com/capitalone/dashboard/model/webhook/github/MergeEvent.java
  core/src/main/java/com/capitalone/dashboard/repository/CollectorItemRepository.java
  core/src/main/java/com/capitalone/dashboard/repository/CommitRepository.java
  core/src/main/java/com/capitalone/dashboard/repository/GitHubRepoRepository.java
  core/src/main/java/com/capitalone/dashboard/repository/GitRequestRepository.java
  core/src/main/java/com/capitalone/dashboard/util/HygieiaUtils.java
  core/src/test/java/com/capitalone/dashboard/util/HygieiaUtilsTest.java
Labels: enhancement, work in progress
