Repository hygieia/hygieia, pull requests merged in 2019-05, with the labels that each got.

#2622 Updates to grab the latest updated collector item
  api-audit/src/main/java/com/capitalone/dashboard/service/CodeReviewAuditServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/CodeQualityServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/CollectorServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/service/GitRequestServiceImpl.java
  api/src/test/java/com/capitalone/dashboard/service/DashboardServiceTest.java
Labels: work in progress

#2782 Feature to collect deployment metrics from Jenkins
  hygieia-jenkins-plugin-alt/src/main/hygieia/HygieiaJenkinsPluginAlt.groovy
Labels: review in progress

#2453 Feature/log analyzer
  UI/src/app/dashboard/core/data-factories/log-data.js
  UI/src/app/dashboard/services/authInterceptor.js
  UI/src/components/templates/widgetsTemplate.html
  UI/src/components/widgets/log/config.html
  UI/src/components/widgets/log/config.js
  UI/src/components/widgets/log/log.less
  UI/src/components/widgets/log/module.js
  UI/src/components/widgets/log/view.html
  UI/src/components/widgets/log/view.js
  UI/src/test-data/logs.json
  api/pom.xml
  api/src/main/java/com/capitalone/dashboard/request/LogAnalysisSearchRequest.java
  api/src/main/java/com/capitalone/dashboard/rest/LogAnalysisController.java
  api/src/main/java/com/capitalone/dashboard/service/LogAnalysisService.java
  api/src/main/java/com/capitalone/dashboard/service/LogAnalysisServiceImpl.java
  api/src/test/java/com/capitalone/dashboard/config/TestAuthConfig.java
  api/src/test/java/com/capitalone/dashboard/config/TestConfig.java
  api/src/test/java/com/capitalone/dashboard/config/TestDefaultAuthConfig.java
  api/src/test/java/com/capitalone/dashboard/rest/LogAnalysisControllerTest.java
  api/src/test/java/com/capitalone/dashboard/service/LogAnalysisServiceImplTest.java
  collectors/cloud/cloudwatch/README.md
  collectors/cloud/cloudwatch/pom.xml
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/Application.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/collector/AwsCloudWatchClientFactory.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/collector/AwsCloudwatchLogAnalyzer.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/collector/AwsCloudwatchLogAnalyzerSettings.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/collector/AwsCloudwatchLogAnalyzerTask.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/model/AwsLogCollectorItem.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/model/CloudWatchJob.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/cloudwatch/model/Series.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/repository/AwsCloudwatchLogAnalyzerRepository.java
  collectors/cloud/cloudwatch/src/main/java/com/capitalone/dashboard/repository/AwsLogCollectorItemRepository.java
  collectors/cloud/cloudwatch/src/main/resources/banner.txt
  collectors/cloud/cloudwatch/src/main/resources/logback.xml
  collectors/cloud/cloudwatch/src/test/java/com/capitalone/dashboard/cloudwatch/collector/AwsCloudwatchLogAnalyzerTaskTest.java
  collectors/cloud/cloudwatch/src/test/java/com/capitalone/dashboard/cloudwatch/collector/AwsCloudwatchLogAnalyzerTest.java
  pom.xml
Labels: enhancement

#2880 NFRR audit result with collectorItemId mapping
  collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/collector/AuditCollectorTask.java
  collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/collector/AuditCollectorUtil.java
  collectors/audit/nfrr/src/main/java/com/capitalone/dashboard/model/Audit.java
  collectors/audit/nfrr/src/test/java/com/capitalone/dashboard/collector/AuditCollectorTaskTest.java
  collectors/audit/nfrr/src/test/java/com/capitalone/dashboard/collector/AuditCollectorTest.java
  collectors/audit/nfrr/src/test/resources/collector_items/items.json
Labels: review in progress
