Repository hygieia/hygieia, pull requests merged in 2019-06, with the labels that each got.

#2167 Karate - Rest API Test Automation Framework for audit api tests
  api-tests/.gitignore
  api-tests/README.md
  api-tests/api-audit/pom.xml
  api-tests/api-audit/src/test/java/basic-auth.js
  api-tests/api-audit/src/test/java/endpoints/ApiRunnerTest.java
  api-tests/api-audit/src/test/java/endpoints/codeReview/peerReview-expected.json
  api-tests/api-audit/src/test/java/endpoints/codeReview/peerReview-params.json
  api-tests/api-audit/src/test/java/endpoints/codeReview/peerReview.feature
  api-tests/api-audit/src/test/java/endpoints/dashboard/dashboardReview-expected.json
  api-tests/api-audit/src/test/java/endpoints/dashboard/dashboardReview-params.json
  api-tests/api-audit/src/test/java/endpoints/dashboard/dashboardReview.feature
  api-tests/api-audit/src/test/java/endpoints/ping/ping.feature
  api-tests/api-audit/src/test/java/karate-config.js
  api-tests/api-audit/src/test/resources/karate-hello-world.jpg
Labels: Good Contribution, review in progress

#2678 Add pull-request data to Bitbucket server collector.
  collectors/scm/bitbucket/pom.xml
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/bitbucketapi/BitbucketApiUrlBuilder.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/bitbucketapi/BitbucketUrlParser.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/DefaultBitbucketServerClient.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/GitCollectorTask.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/GitSettings.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/JSONParserUtils.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/PageMetadata.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/PullRequestCollector.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/collector/SCMHttpRestClient.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/config/SpringConfig.java
  collectors/scm/bitbucket/src/main/java/com/capitalone/dashboard/model/GitRepo.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/bitbucketapi/BitbucketApiUrlBuilderTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/bitbucketapi/BitbucketUrlParserTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/DefaultBitbucketServerClientTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/JSONParserUtilsTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/JsonUtilsTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/PageMetadataTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/PullRequestCollectorTest.java
  collectors/scm/bitbucket/src/test/java/com/capitalone/dashboard/collector/SCMHttpRestClientTest.java
  collectors/scm/bitbucket/src/test/resources/bitbucket-server/pr-response-test-data-1.json
  collectors/scm/bitbucket/src/test/resources/bitbucket-server/test-pagination-is-last-page.json
  collectors/scm/bitbucket/src/test/resources/bitbucket-server/test-pagination-not-last-page.json
Labels: Good Contribution

#2950 Fix NPE breaking admin page config
  collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/HudsonCollectorTask.java
  collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/HudsonSettings.java
Labels: bug

#2955 Ability to create SCM collector items for the code repos part of build
  api/src/main/java/com/capitalone/dashboard/service/BuildServiceImpl.java
  api/src/main/java/com/capitalone/dashboard/settings/ApiSettings.java
  api/src/test/java/com/capitalone/dashboard/service/BuildServiceTest.java
Labels: enhancement

#2969 fix rally widget data fetching
  UI/src/components/widgets/rally/config.js
  api/src/main/java/com/capitalone/dashboard/request/WidgetRequest.java
  api/src/test/java/com/capitalone/dashboard/request/FeatureEntryTest.java
  api/src/test/java/com/capitalone/dashboard/request/WidgetRequestTest.java
Labels: review in progress

#2984 Udeploy config bug fix
  collectors/deploy/udeploy/src/main/java/com/capitalone/dashboard/collector/DefaultUDeployClient.java
  collectors/deploy/udeploy/src/main/java/com/capitalone/dashboard/collector/UDeployCollectorTask.java
  collectors/deploy/udeploy/src/main/java/com/capitalone/dashboard/collector/UDeploySettings.java
  collectors/deploy/udeploy/src/test/java/com/capitalone/dashboard/collector/DefaultUDeployClientTest.java
Labels: review in progress

#2917 Feat/bamboo fast fetch
  collectors/build/bamboo/docker/properties-builder.sh
  collectors/build/bamboo/src/main/java/com/capitalone/dashboard/collector/BambooAsyncFetch.java
  collectors/build/bamboo/src/main/java/com/capitalone/dashboard/collector/BambooSettings.java
  collectors/build/bamboo/src/main/java/com/capitalone/dashboard/collector/DefaultBambooClient.java
Labels: Good Contribution, review in progress

#2990 Audit API Response with collector Item optional fields
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/ArtifactEvaluator.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/BuildEvaluator.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluator.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluator.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegacy.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/DeployEvaluator.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/LibraryPolicyEvaluator.java
  api-audit/src/main/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluator.java
  api-audit/src/test/java/com/capitalone/dashboard/evaluator/ArtifactEvaluatorTest.java
  api-audit/src/test/java/com/capitalone/dashboard/evaluator/CodeQualityEvaluatorTest.java
  api-audit/src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorLegecyTest.java
  api-audit/src/test/java/com/capitalone/dashboard/evaluator/CodeReviewEvaluatorTest.java
  api-audit/src/test/java/com/capitalone/dashboard/evaluator/DeployEvaluatorTest.java
  api-audit/src/test/java/com/capitalone/dashboard/evaluator/PerformanceTestResultEvaluatorTest.java
Labels: review in progress

#3005 [WIP] Build Travis Build failures
  .travis.yml
  pom.xml
Labels: work in progress

#2755 Adding support for GitLab SCM collector to collect issues and pulls (#2730)
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/collector/GitlabGitCollectorTask.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/DefaultGitlabGitClient.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabCommitsResponseMapper.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabGitClient.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabIssuesResponseMapper.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabRequestsResponseMapper.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabUrlUtility.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/model/GitlabCommit.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/model/GitlabCommitStatus.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/model/GitlabIssue.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/model/GitlabNote.java
  collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/model/GitlabRequest.java
  collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collector/DefaultGitlabGitClientTest.java
  collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collector/GitlabGitCollectorTaskTest.java
  collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collector/GitlabUrlUtilityCommitsTest.java
  collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collector/GitlabUrlUtilityIssuesTest.java
  collectors/scm/gitlab/src/test/java/com/capitalone/dashboard/collector/GitlabUrlUtilityMergeRequestsTest.java
Labels: review in progress
